[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "ATRtools"
version = "0.1.0"
description = "Collection of useful tools for ATR and PAGE-XML"
readme = "README.md"
license-files = ["LICENSE"]
authors = [
    { name = "jahtz", email = "dev@janikhtz.de" }
]
requires-python = ">=3.14"
dependencies = [
    "click>=8.5.0",
    "networkx>=3.6.1",
    "numpy>=2.5.3",
    "opencv-python>=5.0.0.93",
    "pypxml>=5.1.0",
    "rich>=15.0.0",
    "scikit-image>=0.26.0",
    "shapely>=2.1.2",
]

[project.scripts]
atrtools = "atrtools:cli"

[tool.ruff.lint.isort]
lines-after-imports = 2
